### ISSUE TITLE
App "com.adguard.mac.adguard" requests Local Network access multiple times

### ISSUE THREAD

**Issue by Critical-Break-5818** [AdguardTeam/AdguardForMac#1521]
Hi Team,

I am using latest version of Adguard as well as macOS. App is asking about LocalNetwork access multiple times even though I have provided the access earlier. 

Also there is no way to remove the app from Local Network. Please help

Please find attached screenshot. 
![Image](https://github.com/user-attachments/assets/a11a6974-3d05-42de-a5d5-82c18f2cc5c3)

**Comment by AlexandrPkhm** [comment]
@Critical-Break-5818 Hello! 

Unfortunately, the image you submitted is corrupted and doesn't load. Please send it again if possible.

We also need your application logs. These are needed to help us diagnose and fix this problem.
Here's what we need you to do:

1. Click **AdGuard icon** in the menu bar *→ Gear → Advanced  → Logging → Logging level → Debug*.
2. Reproduce the problem, then remember the exact time it happened.
3. *Menu → Advanced → Logging → Export Logs and System Info.…*.
4. Send this file to [qa@adguard.com](mailto:qa@adguard.com):
    — include `[mac]` keyword and `ISSUE_NUMBER` in the subject of your email
    — specify the exact time when the issue occurred

**Comment by Critical-Break-5818** [comment]
<img width="798" alt="Screenshot 2024-12-26 at 10 51 59 AM" src="https://github.com/user-attachments/assets/cd191659-7669-4054-a9b4-c48472b44812" />

**Comment by Critical-Break-5818** [comment]
Hi Team,

I am not sure why it is not reported earlier by other users. 

Anyways I have enabled low-level debug mode in Adguard. If Adguard request again for local network then I will share logs. Meantime I have already shared screenshot.

**Comment by AlexandrPkhm** [comment]
@Critical-Break-5818 The issue you mention was raised and later dismissed by our team as it occurred on the beta version of macOS Sequoia and was later fixed in the macOS update. 

Could you please let us know which version of macOS and which version of AdGuard you are running on your device?

**Comment by Critical-Break-5818** [comment]
Macos is 15.2 latest version. Chipset M4. 

Adguard version - 2.16.1

and issue is NOT fixed. Other user has also faced similar issue #1477

**Comment by AlexandrPkhm** [comment]
@Critical-Break-5818 Currently it seems that the issue is related to an Apple bug. However, we will investigate it further.

**Comment by dalDevelo** [comment]
+1 to this. I currently have 8 copies of com.adguard.mac.adguard under local network connections. This did indeed start when I installed macOS Sequoia Beta and I noticed 2 copies of the AdGuard item under Local Network. I was also running the beta version of AdGuard for Mac at the time.

In an attempt to resolve this, I fully uninstalled AdGuard Beta following [these instructions](https://adguard.com/kb/adguard-for-mac/installation/#uninstall) (including Advanced instructions) and re-installed the production version of AdGuard, which just created additional com.adguard.mac.adguard items under Local Network connections. I've since installed the production version of macOS and AdGuard, and followed the detailed uninstall process for AdGuard again, which just continues to create additional items under Local Network connections. Which seems to be why I now have 8 entries.

Of those 8 entries, only the top one can be toggled ON+OFF (the 7 further entries below cannot, though if I attempt to toggle those, it toggles the top AdGuard item in my list to OFF only). Right clicking on the LAST entry in the list and selecting "Show in Finder" results in a finder window opening to the network extension, attempting this on the top 7 entries in the list has no effect at all.

**Comment by Critical-Break-5818** [comment]
Correct i am also facing the same but AdGuard team saying its not bug.. its serious issue

**Comment by dalDevelo** [comment]
Well I believe they are saying it's a macOS bug. Given the state of the networking components in early Sequoia releases (and still, to a point) I have a hard time believing otherwise. It looks like they are on it and it has been tagged for AdGuard release v2.17. Hopefully they are able to work it out with Apple in time for that release🤞🏼.

Be patient, it's not a show stopper, but a minor annoyance. I'm confident they'll sort it out 😊

**Comment by Critical-Break-5818** [comment]
If its macos bug then it should be happening with other apps as well. But its occurring only in Adguard

**Comment by Critical-Break-5818** [comment]
@AlexandrPkhm  Any update on this issue?

**Comment by unknownsolo** [comment]
I have the same issue. Any update on how to remove these entries?

**Comment by Critical-Break-5818** [comment]
Reinstall macos.. Uninstalling Adguard wont remove those entries. 

Reinstall macos then install Adguard. After that TURN OFF AUTO UPDATE IN ADGUARD. You are good then. If you update Adguard then again one more entry will showed up in Local Network

**Comment by unknownsolo** [comment]
If I am reinstalling MacOS just to fix this, I am not putting this crappy app on it again!

**Comment by Critical-Break-5818** [comment]
For Dev team, its p4 issue. For me its p1 issue.

**Comment by aturtsev** [comment]
I agree with all of the above. I have a similar problem after removing AdGuard. macOS Sequoia 15.3.1, Apple M3 Pro
<img width="600" alt="Image" src="https://github.com/user-attachments/assets/29b6745a-2f31-44ad-9d5c-83a605c80c96" />

**Comment by dalDevelo** [comment]
> If its macos bug then it should be happening with other apps as well. But its occurring only in Adguard

That's not entirely true. I have 2 entries for Spotify too! (See image).

I've just installed the latest macOS 15.4 (beta 2) and many of my apps listed under Local Network were deleted as part of that update, though not AdGuard or Spotify, unfortunately. But it appears Apple are doing some work on this section of settings...or it's yet more bugs with Sequoia's network components / settings??

![Image](https://github.com/user-attachments/assets/ec7d70a7-579a-4ebf-8102-31e2f6521d3d)

**Comment by GlyphSH** [comment]
Does not remove itself even after uninstall. Uninstallation [guide](https://adguard.com/kb/adguard-for-mac/installation/#uninstall) did not help.

**Comment by IceBear-12** [comment]
Hello, maybe you can take a look at the answer to the [issue](https://github.com/AdguardTeam/AdguardForMac/issues/1584) the AdGuard Support Team gave me. I have the same problem, but it seems like a macOS problem actually. At least the latest version of macOS still has these problems. They cannot fix this on their end as the list of those entries is managed by macOS. This issue is not limited to AdGuard either.

**Comment by dalDevelo** [comment]
Interested to know if anyone who posted here has installed the 2.18 beta and whether this has resolved the issue for them? I don't see any mention of this being resolved in the 2.18 beta 1 release notes and believed this was for Apple to fix, though the latest adguard-bot label changes to "Resolution:Fixed" and "Status:Done" makes me wonder if the AdGuard Team we able to find a solution themselves and this is part of the 2.18 release? (As labelled)

**Comment by AlexandrPkhm** [comment]
@dalDevelo Our development team has done everything necessary to confirm that this behavior is not related to AdGuard. I want to emphasize that the same behavior occurs with other applications as well, which strongly suggests that the issue is on Apple’s side.

For example, I also have a whole collection of Google Chrome instances appearing in that list.

![image](https://github.com/user-attachments/assets/61452add-dbac-4bb6-bde9-f2d1769ce254)

**Comment by dalDevelo** [comment]
@AlexandrPkhm thanks for confirming. I was just confused due to the labels applied to the issue on closure. I'm aware of multiple apps showing, I posted evidence of that myself back in March.

I've actually resolved the issue now anyway by removing a couple of system plist files which can be removed whilst in recovery mode to fix this. Now back to a tidy 7 item Local Network list.
